version: "2"
services:
  ai-assistant:
    restart: always
    privileged: true
    labels:
      io.balena.features.kernel-modules: 1
    devices:
      - /dev/snd
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.ai-assistant

  balena-starter-interface:
    build:
      context: .
      dockerfile: Dockerfile.interface
    environment:
      NETWORK_MODE: bridge # Tell the app if running in `bridge` or `host` network mode
    restart: always
    ports:
      - "80:80"
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1

  python-wifi-connect:
    image: ghcr.io/balena-labs-research/python-wifi-connect:0.0.12
    environment:
      # Listening IP and port
      PWC_HOST: bridge # `bridge` specifies that this is on the bridge network and to use container name
      PWC_PORT: 9090

      # Hotspot details
      PWC_HOTSPOT_SSID: "AI Voice Assistant" # Name as it appears in list of WiFi networks

      # Required system variables
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    network_mode: "host"
    restart: always
    volumes:
      - "pwc_db:/app/db" # Optional if not setting the hotspot ssid and password via the API
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
    privileged: true # This can be removed if you do not need the LED connectivity indicator.

volumes:
  pwc_db:
